# Generated by Django 3.2.2 on 2021-05-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('partition_country', models.TextField(blank=True, null=True)),
                ('kpi1', models.TextField(blank=True, null=True)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('vin_hash', models.IntegerField(blank=True, null=True)),
                ('production_date', models.TextField(blank=True, null=True)),
                ('countnull_n_expected', models.IntegerField(blank=True, db_column='countNull_N_expected', null=True)),
                ('vin', models.IntegerField(blank=True, null=True)),
                ('vin_vl', models.IntegerField(blank=True, null=True)),
                ('response_ecu_id', models.TextField(blank=True, null=True)),
                ('did_id', models.TextField(blank=True, null=True)),
                ('partition_region', models.TextField(blank=True, null=True)),
                ('kpi9', models.TextField(blank=True, null=True)),
                ('derived_event', models.TextField(blank=True, null=True)),
                ('kpi2', models.TextField(blank=True, null=True)),
                ('vehicle_line', models.TextField(blank=True, null=True)),
                ('sell_country', models.TextField(blank=True, null=True)),
                ('kpi5', models.TextField(blank=True, null=True)),
                ('kpi6', models.TextField(blank=True, null=True)),
                ('kpi7', models.TextField(blank=True, null=True)),
                ('kpi4', models.TextField(blank=True, null=True)),
                ('countnull_expected', models.IntegerField(blank=True, db_column='countNull_expected', null=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DADOS',
                'managed': False,
            },
        ),
    ]
